Bug 2071914: azure: default empty environment to AzurePublicCloud
openshift/cloud-network-config-controller pull request #36
Opened 2022-04-19 10:29 UTC by squeed

Annoyingly, the CNO does a silly thing and explicitly passes an empty string. Doh. So, work around that.

/cc @andreaskaris

2022-04-19 12:01 UTC, andreaskaris requested changes

2022-04-19 12:08 UTC, squeed commented on pkg/cloudprovider/azure.go
> +	tenantID, err := a.readSecretData("azure_tenant_idf")
Oops!

2022-04-19 12:09 UTC, squeed commented on pkg/cloudprovider/azure.go
> +			name = "AzurePublicCloud"
Yeah, ideally we fix this in CNO as well.

2022-04-19 14:49 UTC, andreaskaris commented
/retest-required

2022-04-19 14:49 UTC, andreaskaris commented
/lgtm

2022-04-19 14:50 UTC, andreaskaris approved these changes

2022-04-19 16:27 UTC, merged

2022-04-20 08:57 UTC, squeed commented
/cherry-pick release-4.10