OCPBUGS-1629: Add resolver to handle custom endpoints
openshift/cloud-network-config-controller pull request #61
Opened 2022-09-26 16:57 UTC by kyrtapz

Based on https://github.com/openshift/cloud-network-config-controller/pull/60

This patch adds a custom resolver to only set a custom endpoint on EC2 service.

/assign @andreaskaris 

(cherry picked from commit 489c81d07e4bd5fbe93fd400cb27def4ab0ef70d)
Signed-off-by: Patryk Diak <pdiak@redhat.com>

2022-09-28 15:49 UTC, kyrtapz commented
/retest

2022-09-28 19:13 UTC, andreaskaris requested changes
nit for the commit message, can we change that to something along these lines:

AWS: Use platform-api-url override only for EC2 service endpoint

CNO sets platform-api-url param (APIOverride) to overwrite the EC2
service endpoint. Prior to this patch, the AWS cloud provider
unconditionally overwrote the endpoint URL for all endpoints. This 
caused issues with other service endpoints such as STS. Add a custom
resolver to only set the custom endpoint for EC2 service endpoint

2022-09-29 09:45 UTC, andreaskaris commented
/lgtm

2022-09-29 15:39 UTC, kyrtapz commented
Failures not related to CNCC changes:
```
{  2 events happened too frequently
event happened 21 times, something is wrong: ns/openshift-etcd-operator deployment/etcd-operator - reason/UnhealthyEtcdMember unhealthy members: ip-10-0-135-119.ec2.internal
event happened 22 times, something is wrong: ns/openshift-etcd-operator deployment/etcd-operator - reason/UnhealthyEtcdMember unhealthy members: ip-10-0-156-120.ec2.internal}
```
/override ci/prow/e2e-aws-serial

2022-09-29 15:43 UTC, merged

2022-09-29 15:51 UTC, kyrtapz commented
/cherry-pick release-4.11